### ISSUE TITLE
Informative error when the entry is missing a `bump: `

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/yaml-changelog#10]

**Comment by MaxGhenis** [comment]
Just bumping this. Empty changelog_entry.yaml files produce this message:
```
build-changelog changelog.yaml --output changelog.yaml --update-last-date --start-from 0.0.1 --append-file changelog_entry.yaml
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/bin/build-changelog", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/yaml_changelog/build.py", line 267, in main
    cl = Changelog(
  File "/opt/hostedtoolcache/Python/3.9.[16](https://github.com/PolicyEngine/policyengine-us/actions/runs/4475331706/jobs/7864646342#step:4:17)/x64/lib/python3.9/site-packages/yaml_changelog/build.py", line 82, in __init__
    self._parse_from_yaml(self.file, append)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/yaml_changelog/build.py", line 105, in _parse_from_yaml
    self.entries.extend(yaml.safe_load(f))
TypeError: 'NoneType' object is not iterable
make: *** [Makefile:[20](https://github.com/PolicyEngine/policyengine-us/actions/runs/4475331706/jobs/7864646342#step:4:21): changelog] Error 1
```
With more new volunteers, it'd be helpful for them to know what to do.
